name: deploy

on:
  push:
      branches:
        - master

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16.13.1'
       - name: Build web-app
          run: |
            npm ci
            npm run build
       - name: Deploy to master
         uses: HTTyminski
         with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build